---
- hosts: localhost
  connection: local
  roles:
    - arch
  vars_prompt:
    - name: user
      prompt: Enter your username
      private: false
    - name: password
      prompt: Enter your password
      private: true
    - name: git_work_name
      prompt: Enter your git name (work)
      private: false
    - name: git_work_email
      prompt: Enter your git email (work)
      private: false
    - name: git_private_name
      prompt: Enter your git name (private)
      private: false
    - name: git_private_email
      prompt: Enter your git email (private)
      private: false
    - name: nvim_coc_intelephense
      prompt: Enter Intelephense premium key
      private: false

