---
- name: install applications
  pacman:
    name:
      - anki
      - feh
      - gimp
      - networkmanager-fortisslvpn
      - obs-studio
      - pcmanfm
      - ranger
      - vlc

- name: install applications from aur
  aur:
    name: 
      - anydesk-bin
      - teams
  become: true
  become_user: aur

- name: copy applications
  copy:
    src: apps
    dest: ~/
  become: true
  become_user: "{{ user }}"
