---
- name: install utilities
  pacman:
    name:
      - base-devel
      - curl
      - htop
      - less
      - nmap
      - openssh
      - rsync
      - which

- name: install applications
  pacman:
    name:
      - chromium
      - feh
      - firefox
      - gimp
      - obs-studio
      - pcmanfm
      - ranger
      - vlc

- name: install aur applications
  aur:
    name:
      - codium
      - yay
  become: true
  become_user: aur_builder
