---
- name: install applications
  pacman:
    name:
      - feh
      - gimp
      - obs-studio
      - pcmanfm
      - ranger
      - vlc

- name: install applications from aur
  aur:
    name: screen-desktop-bin
  become: true
  become_user: aur

- name: copy applications
  copy:
    src: apps
    dest: ~/
  become: true
  become_user: "{{ user }}"
