---
- name: install utilities
  pacman:
    name:
      - curl
      - ffmpeg
      - fzf
      - htop
      - intel-ucode
      - less
      - nmap
      - ripgrep
      - rsync
      - unzip
      - which

- name: install applications
  pacman:
    name:
      - feh
      - gimp
      - obs-studio
      - pcmanfm
      - ranger
      - vlc
