---
- name: install audio management
  pacman:
    name:
      - pulseaudio
      - pavucontrol

- name: install bluetooth
  pacman:
    name:
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - bluez-utils

- name: configure bluetooth
  copy:
    src: audio/
    dest: /etc/

