---
- name: install browsers
  pacman:
    name:
      - chromium
      - firefox

- name: get firefox's profile dir
  shell: grep '^Default=.*\.default-release$' ~/.mozilla/firefox/profiles.ini | sed s/^Default=//
  register: firefox_profile_dir

- name: remove white loading screen in firefox
  copy:
    src: firefox/
    dest: ~/.mozilla/firefox/{{ firefox_profile_dir.stdout }}/
