---
- name: install browsers
  pacman:
    name:
      - chromium
      - firefox

- name: get firefox's profile dir
  shell: grep '^Default=.*\.default-release$' ~/.mozilla/firefox/profiles.ini | sed s/^Default=//
  register: firefox_profile_dir

- name: remove white loading screen in firefox
  copy:
      src: firefox/
      dest: ~/.mozilla/firefox/{{ firefox_profile_dir.stdout }}/

- name: download install script for tridactyl native messenger
  get_url:
    url: https://raw.githubusercontent.com/tridactyl/tridactyl/master/native/install.sh
    dest: /tmp/trinativeinstall.sh
  become: true
  become_user: "{{ user }}"

- name: install tridactyl native messenger
  shell: bash /tmp/trinativeinstall.sh master
  become: true
  become_user: "{{ user }}"

- name: configure tridactyl
  copy:
    src: tridactyl
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"
