---
- name: install Docker
  pacman:
    name: docker

- name: install Docker-Compose
  pacman:
    name: docker-compose

- name: enable Docker daemon
  systemd:
    name: docker.service
    state: started
    enabled: true

- name: add user to Docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
