---
- name: install neovim
  pacman:
    name: neovim

- name: create vim autoload directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory
  become: true
  become_user: "{{ user }}"

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/
  become: true
  become_user: "{{ user }}"

- name: configure vim
  copy:
    src: nvim
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: install and update vim plugins
  command: /usr/bin/nvim -c ':PlugInstall' -c ':UpdateRemotePlugins' -c ':qall'
  become: true
  become_user: "{{ user }}"

- name: set vim as default
  lineinfile:
    path: /etc/environment
    regexp: '^EDITOR=.*'
    line: EDITOR=/usr/bin/nvim

- name: install vscode
  aur:
    name:
      - vscodium-bin
  become: true
  become_user: aur
