---
- name: install neovim
  pacman:
    name: neovim

- name: create vim autoload directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory
  become: true
  become_user: "{{ user }}"

- name: configure vim
  copy:
    src: nvim
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: set vim as default
  lineinfile:
    path: /etc/environment
    regexp: '^EDITOR=.*'
    line: EDITOR=/usr/bin/nvim

- name: configure markdownlint
  copy:
    src: markdownlint
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: install nvim python module (for vdebug)
  pip:
    name: pynvim
    extra_args: --user

- name: install vscode
  aur:
    name:
      - vscodium-bin
  become: true
  become_user: aur
