---
- name: install neovim
  pacman:
    name: neovim

- name: configure vim
  copy:
    src: nvim
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: set vim as default
  lineinfile:
    path: /etc/environment
    regexp: '^EDITOR=.*'
    line: EDITOR=/usr/bin/nvim

- name: install python provider
  pacman:
    name: python-pynvim

- name: install node provider
  yarn:
    name: neovim
    global: yes
      
- name: install lsp
  yarn:
    name: vscode-langservers-extracted
    global: yes

- name: configure markdownlint
  copy:
    src: markdownlint
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: install vscode
  aur:
    name: vscodium-bin
  become: true
  become_user: aur

