---
- name: configure git globally
  copy:
    src: git/.gitconfig
    dest: ~/
  become: true
  become_user: "{{ user }}"

- name: create work project directory
  file:
    name: ~/Projects
    state: directory
  become: true
  become_user: "{{ user }}"

- name: configure git for work
  template:
    src: git/work_config.j2
    dest: ~/Projects/.gitconfig
  become: true
  become_user: "{{ user }}"

- name: create private project directory
  file:
    name: ~/MyProjects
    state: directory
  become: true
  become_user: "{{ user }}"

- name: configure git for private
  template:
    src: git/private_config.j2
    dest: ~/MyProjects/.gitconfig
  become: true
  become_user: "{{ user }}"

- name: configure gitignore globally
  copy:
    src: git/ignore
    dest: ~/.config/git/
  become: true
  become_user: "{{ user }}"

- name: install meld
  pacman:
    name: meld
