---
- name: install Xorg
  pacman:
    name:
      - mesa
      - xorg-server
      - xorg-xinit

- name: install display management
  pacman: 
    name: arandr

- name: configure screenlayout
  copy:
    src: gui/screenlayout/
    dest: ~/.screenlayout
  become: true
  become_user: "{{ user }}"

- name: configure natural scrolling
  copy:
    src: gui/40-libinput.conf
    dest: /usr/share/X11/xorg.conf.d/
