---
- name: configure low battery
  copy:
    src: laptop/99-lowbat.rules
    dest: /etc/udev/rules.d/

- name: store backlight directory name
  shell: "ls /sys/class/backlight"
  register: backlight_dir

- name: configure permissions for brightness
  template:
    src: laptop/backlight.rules.j2
    dest: /etc/udev/rules.d/backlight.rules
  when: backlight_dir.stdout != ""
