---
- name: perform full upgrade
  pacman:
    update_cache: true
    upgrade: true

- name: install aur dependencies
  pacman:
    name: base-devel

- name: install paru
  aur:
    name: paru
  become: true
  become_user: aur

- name: enable color
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#Color'
    line: Color

- name: reverse suggestions
  lineinfile:
    path: /etc/paru.conf
    regexp: '^#BottomUp'
    line: BottomUp

