---
- name: perform full upgrade
  pacman:
    update_cache: true
    upgrade: true

- name: install aur dependencies
  pacman:
    name: base-devel

- name: install yay
  aur:
    name: yay
  become: true
  become_user: aur
