---
- name: install font
  aur:
    name: nerd-fonts-source-code-pro
  become: true
  become_user: aur

- name: install emoji font
  pacman:
    name: noto-fonts-emoji

- name: install tmux
  pacman:
    name: tmux

- name: configure tmux
  copy:
    src: tmux/
    dest: ~/
  become: true
  become_user: "{{ user }}"

- name: install fish shell
  pacman:
    name: fish

- name: configure fish
  copy:
    src: fish
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: install terminal utils
  aur:
    name:
      - zoxid
      - starship
  become: true
  become_user: aur

- name: configure starship
  copy:
    src: starship/starship.toml
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: install alacritty
  pacman:
    name: alacritty

- name: configure alacritty
  copy:
    src: alacritty
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

