---
- name: install font
  pacman:
    name: adobe-source-code-pro-fonts

- name: install tmux
  pacman:
    name: tmux

- name: configure tmux
  copy:
    src: tmux/
    dest: ~/

- name: install fish shell
  pacman:
    name: fish

- name: configure fish
  copy:
    src: fish
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: install alacritty
  pacman:
    name: alacritty

- name: configure alacritty
  copy:
    src: alacritty
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"
