---
- name: install sudo
  pacman:
    name: sudo

- name: create user
  user:
    name: "{{ user }}"
    groups:
      - wheel
      - docker

- name: create user for aur
  user:
    name: aur

- name: configure sudoers
  copy:
    src: "{{ item }}"
    dest: /etc/sudoers.d/
    mode: 0440
    validate: /usr/bin/visudo -cf %s
  with_items:
    - user/sudoer-wheel
    - user/sudoer-aur
