---
- name: install sudo
  pacman:
    name: sudo

- name: create user
  user:
    name: "{{ user }}"
    groups:
      - wheel

- name: create user for aur
  user:
    name: aur
    groups: wheel

- name: configure sudoers
  copy:
    src: "{{ item }}"
    dest: /etc/sudoers.d/
    mode: 0440
    validate: /usr/bin/visudo -cf %s
  loop:
    - user/1-sudoer-wheel
    - user/2-sudoer-aur
