---
- name: install utilities
  pacman:
    name:
      - bat
      - curl
      - dunst
      - exa
      - fd
      - ffmpeg
      - fzf
      - github-cli
      - htop
      - imagemagick
      - intel-ucode
      - jdk-openjdk
      - jq
      - kubectl
      - less
      - man-db
      - nmap
      - nodejs
      - ntfs-3g
      - ripgrep
      - rsync
      - tldr
      - tree
      - unrar
      - unzip
      - which
      - yarn

- name: install utilities (aur)
  aur:
    name: rn
  become: true
  become_user: aur

- name: configure ripgrep
  copy:
    src: ripgrep
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: set ripgrep config path
  lineinfile:
    path: /etc/environment
    regexp: '^RIPGREP_CONFIG_PATH=.*'
    line: "RIPGREP_CONFIG_PATH=/home/{{ user }}/.config/ripgrep/config"

- name: set fzf to use ripgrep
  lineinfile:
    path: /etc/environment
    regexp: '^FZF_DEFAULT_COMMAND=.*'
    line: FZF_DEFAULT_COMMAND=rg --files --hidden

