---
- name: install utilities
  pacman:
    name:
      - bat
      - curl
      - ffmpeg
      - fzf
      - htop
      - intel-ucode
      - jdk-openjdk
      - less
      - nmap
      - nodejs
      - ripgrep
      - rsync
      - unrar
      - unzip
      - which
      - yarn

- name: configure ripgrep
  copy:
    src: ripgrep
    dest: ~/.config/
  become: true
  become_user: "{{ user }}"

- name: set ripgrep config path
  lineinfile:
    path: /etc/environment
    regexp: '^RIPGREP_CONFIG_PATH=.*'
    line: "RIPGREP_CONFIG_PATH=/home/{{ user }}/.config/ripgrep/config"

- name: set fzf to use ripgrep
  lineinfile:
    path: /etc/environment
    regexp: '^FZF_DEFAULT_COMMAND=.*'
    line: FZF_DEFAULT_COMMAND=rg --files --hidden

