---
- name: install Xorg
  pacman:
    name:
      - mesa
      - xorg-server
      - xorg-xinit

- name: install rofi
  pacman:
    name: rofi

- name: install i3
  pacman:
    name:
      - picom
      - i3-gaps
      - i3status
      - i3lock

- name: set i3 as default
  copy:
    src: i3/.xinitrc
    dest: ~/
  become: true
  become_user: "{{ user }}"

- name: configure i3
  copy:
    src: i3/config
    dest: ~/.config/i3
  become: true
  become_user: "{{ user }}"
