---
- name: install window manager utils
  pacman:
    name:
      - dmenu
      - picom
      - slock
      - xmobar

- name: install xmonad
  pacman:
    name: 
      - xmonad
      - xmonad-contrib

- name: set xmonad as default
  copy:
    src: xmonad/.xinitrc
    dest: ~/
  become: true
  become_user: "{{ user }}"

- name: configure xmonad
  copy:
    src: xmonad/xmonad.hs
    dest: ~/.xmonad/
  become: true
  become_user: "{{ user }}"
