---
- name: install window manager utils
  pacman:
    name:
      - picom
      - dmenu
      - xmobar
      - slock

- name: install leftwm
  aur:
    name: leftwm
  become: true
  become_user: aur

- name: set leftwm as default
  copy:
    src: leftwm/.xinitrc
    dest: ~/
  become: true
  become_user: "{{ user }}"

- name: configure leftwm
  copy:
    src: leftwm/config.toml
    dest: ~/.config/leftwm/
  become: true
  become_user: "{{ user }}"

- name: configure leftwm theme
  copy:
    src: leftwm/themes
    dest: ~/.config/leftwm/
    mode: preserve
  become: true
  become_user: "{{ user }}"
