---
- name: install leftwm
  pacman:
    name:
      - picom
      - dmenu
      - xmobar
      - slock
      - leftwm

- name: set leftwm as default
  copy:
    src: leftwm/.xinitrc
    dest: ~/
  become: true
  become_user: "{{ user }}"

- name: configure leftwm
  copy:
    src: leftwm/config.toml
    dest: ~/.config/leftwm/
  become: true
  become_user: "{{ user }}"

- name: configure leftwm theme
  copy:
    src: leftwm/themes
    dest: ~/.config/leftwm/
  become: true
  become_user: "{{ user }}"
