---
- name: install leftwm
  pacman:
    name:
      - picom
      - dmenu
      - polybar
      - leftwm

- name: set leftwm as default
  copy:
    src: leftwm/.xinitrc
    dest: ~/
  become: true
  become_user: "{{ user }}"

- name: configure leftwm
  copy:
    src: leftwm/config.toml
    dest: ~/.config/leftwm/
  become: true
  become_user: "{{ user }}"

- name: create leftwm themes dir
  file:
    path: ~/.config/leftwm/themes
    state: directory
  become: true
  become_user: "{{ user }}"

- name: configure leftwm theme
  file:
    src: /usr/share/leftwm/themes/basic_polybar
    dest: ~/.config/leftwm/themes
    state: link
  become: true
  become_user: "{{ user }}"
