version: "2.1"

services:
  nzbget:
    image: linuxserver/nzbget
    restart: unless-stopped
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 6789:6789
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    networks:
      - nzbget-net

networks:
  nzbget-net:
   ipam:
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
